global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'jeonseguard-backend'
    metrics_path: '/actuator/prometheus'
    honor_labels: true
    static_configs:
      - targets: ['springboot-app:8080']
