name: Deploy to GCP

on:
  push:
    branches:
      - develop 
      - fix/ci-cd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy on GCP VM using sshpass
        run: |
          echo "${{ secrets.GCP_SSH_KEY }}" > gcp_key.pem
          chmod 600 gcp_key.pem

          sshpass -p "${{ secrets.GCP_PASSPHRASE }}" ssh -o StrictHostKeyChecking=no -i gcp_key.pem ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_HOST }} << EOF
            cd /home/${{ secrets.GCP_USERNAME }}
            docker compose down
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}
            docker compose up -d
          EOF
